# Generated by Django 5.1.1 on 2024-09-09 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
                ('profile_pic', models.FileField(upload_to='users/images')),
                ('birth_date', models.DateField(null=True)),
                ('facebook_profile', models.TextField(null=True)),
                ('country', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
