# Generated by Django 5.1.1 on 2024-09-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_active'),
        ('users', '0004_alter_user_last_login'),
    ]

    operations = [
    ]
