# Generated by Django 5.1.1 on 2024-09-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_pic',
            field=models.FileField(blank=True, null=True, upload_to='projects/images/profile_image'),
        ),
    ]
