# Generated by Django 5.1.1 on 2024-09-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_project_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_time',
            field=models.DateTimeField(),
        ),
    ]
