# Generated by Django 4.2.16 on 2024-09-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='projects.tag'),
        ),
    ]
