# Generated by Django 4.2.16 on 2024-09-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_pic',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/profile_image'),
        ),
    ]
